home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('', views.hello, name='hello')
]

remail/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url="home/", permanent=True)),
    path('user/', include('user.urls')),
    path('remailbox/', include('remailbox.urls')),
    path('mypage/', include('mypage.urls')),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('login/', views.login, name='login'),
    # path('logout/', views.logout, name= 'logout'), #수정
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def hello(request):
    #수정
    context = {}

    login_session = request.session.get('login_session', '')

    if login_session =='':
        context['login_session'] = False
    else:
        context['login_session'] = True

    return render(request, 'home/index.html', context)

home/templates/home/index.html
<!DOCTYPE html>
{% load static %}
<html lang="kr">
    <head>
        <meta charset="UTF-8">
        <title>home</title>
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
    </head>
    <body>
        <!-- <h1>Hello!</h1>
        <a href="/"><button>home</button></a>

        {% if login_session %}
        <a href="{% url 'user:logout' %}"><button>log out</button></a>
        {% else %}
        <a href="{% url 'user:login' %}"><button>log in</button></a>
        <a href="{% url 'user:register' %}"><button>sign up</button></a>
        {% endif %} -->
        <div class="section" >
            <div class="re-mail">Re-mail</div>
            <div class='button'><a href="{% url 'user:login' %}"><input type="button" id="loginb" value="log in"></a></div>
            <div class='button'><a href="{% url 'user:register' %}"><input type="button" id="signupb" value="Sign up"></a></div>
            <div class='button'><input type="button" id="about" value="about" onClick="location.href='/'"></div>
        </div>
        {% block contents %}
            {% if messages %}
                {% for message in messages %}
                    <script type="text/javascript">
                        alert("{{ message.message }}")
                    </script>
                {% endfor %}
            {% endif %}
        {% endblock %}
    </body>
</html>